# Generated by Django 3.2.20 on 2024-04-17 12:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_account_other_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='other_skills',
            field=jsonfield.fields.JSONField(default=list, null=True, verbose_name='Other skills'),
        ),
    ]
