# Generated by Django 3.2.20 on 2024-04-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_account_other_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='other_skills',
        ),
    ]
